# Generated by Django 2.2.2 on 2019-06-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('isbn', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=250)),
                ('number_of_pages', models.PositiveIntegerField()),
                ('publisher', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
